name: flutterProject
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  intro_slider: ^2.2.8
  bottom_navy_bar: ^5.3.2
  http: ^0.12.0+4
  splashscreen: ^1.2.0
  flutter_launcher_icons: ^0.7.4
  flutter:
    sdk: flutter
  sqflite:
  path:

flutter_icons:
  ios: true
  android: true
  image_path_ios: "asset/images/Liliana.png"
  image_path_android: "asset/images/Liliana.png"

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  
  assets:
     - asset/images/Aleister.png
     - asset/images/annette.png
     - asset/images/D'Arcy.png
     - asset/images/diao-.png
     - asset/images/illumia.png
     - asset/images/krixi.png
     - asset/images/liliana.png
     - asset/images/natalya.png
     - asset/images/preyta.png
     - asset/images/sephera.png
     - asset/images/tulen.png
     


cupertino_icons: ^0.1.2  
splashscreen: any
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
