name: flutterProject
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  intro_slider: ^2.2.8
  bottom_navy_bar: ^5.3.2
  http: ^0.12.0+4
  splashscreen: ^1.2.0
  flutter_launcher_icons: ^0.7.4
  flutter:
    sdk: flutter
  sqflite:
  path:

flutter_icons:
  ios: true
  android: true
  image_path_ios: "asset/images/tik1.png"
  image_path_android: "asset/images/tik1.png"

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  
  assets:
     - asset/images/tik1.png
     - asset/images/tik2.png
     - asset/images/tik3.png
     - asset/images/tik4.png
     - asset/images/tik5.png
     - asset/images/tik6.png
     - asset/images/tik7.png
     - asset/images/tik8.png
     - asset/images/tik9.png
     - asset/images/tik10.png
     - asset/images/tik11.png
     - asset/images/tik12.png
     - asset/images/tik13.png
     - asset/images/tik14.png
     - asset/images/tik15.png
     - asset/images/tik16.png
     - asset/images/tik17.png
     - asset/images/tik18.png
     - asset/images/photo_museum.png
     - asset/images/photo_school.png
     - asset/images/photo_coffee_shop.png
     - asset/images/blood-type (1).png
     - asset/images/blood-type (2).png
     - asset/images/blood-type (3).png
     - asset/images/blood-type.png
     - asset/images/blood-donation.png


cupertino_icons: ^0.1.2  
splashscreen: any
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
